In [1]:
!nvidia-smi

Sun Dec  5 08:10:36 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.44       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   71C    P8    33W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
import numpy as np
import pandas as pd


In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
# data = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/AllStatesAndTerritoriesQTR4FY21.xlsx', sheet_name = ['ALABAMA', 'ALASKA', 'ARIZONA', 'ARKANSAS', 'CALIFORNIA', 'COLORADO', 'CONNECTICUT', 'DELAWARE', 'FLORIDA', 'GEORGIA', 'GUAM', 'IDAHO', 'ILLINOIS', 'INDIANA', 'IOWA', 'KANSAS', 'KENTUCKY', 'LOUISIANA', 'MAINE', 'MARYLAND', 'MASSACHUSETTS', 'MICHIGAN', 'MINNESOTA', 'MISSISSIPPI', 'MISSOURI', 'MONTANA', 'NEBRASKA', 'NEVADA', 'NEW HAMPSHIRE', 'NEW JERSEY', 'NEW MEXICO', 'NEW YORK', 'NORTH CAROLINA', 'NORTH DAKOTA', 'NORTHERN MARIANA ISLANDS', 'OHIO', 'OKLAHOMA', 'OREGON', 'PENNSYLVANIA', 'PUERTO RICO', 'RHODE ISLAND', 'SOUTH CAROLINA', 'SOUTH DAKOTA', 'TENNESSEE', 'TEXAS', 'UTAH', 'VERMONT', 'VIRGIN ISLANDS OF THE U.S.', 'VIRGINIA', 'WASHINGTON', 'WEST VIRGINIA', 'WISCONSIN', 'WYOMING'])
data = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/AllStatesAndTerritoriesQTR4FY21.xlsx', sheet_name = None)
# data = pd.read_csv('AllStatesAndTerritoriesQTR4FY21.csv')

In [5]:
data.keys()

dict_keys(['ALABAMA', 'ALASKA', 'ARIZONA', 'ARKANSAS', 'CALIFORNIA', 'COLORADO', 'CONNECTICUT', 'DELAWARE', 'FLORIDA', 'GEORGIA', 'GUAM', 'IDAHO', 'ILLINOIS', 'INDIANA', 'IOWA', 'KANSAS', 'KENTUCKY', 'LOUISIANA', 'MAINE', 'MARYLAND', 'MASSACHUSETTS', 'MICHIGAN', 'MINNESOTA', 'MISSISSIPPI', 'MISSOURI', 'MONTANA', 'NEBRASKA', 'NEVADA', 'NEW HAMPSHIRE', 'NEW JERSEY', 'NEW MEXICO', 'NEW YORK', 'NORTH CAROLINA', 'NORTH DAKOTA', 'NORTHERN MARIANA ISLANDS', 'OHIO', 'OKLAHOMA', 'OREGON', 'PENNSYLVANIA', 'PUERTO RICO', 'RHODE ISLAND', 'SOUTH CAROLINA', 'SOUTH DAKOTA', 'TENNESSEE', 'TEXAS', 'UTAH', 'VERMONT', 'VIRGIN ISLANDS OF THE U.S.', 'VIRGINIA', 'WASHINGTON', 'WEST VIRGINIA', 'WISCONSIN', 'WYOMING'])

In [6]:
df = pd.concat(data[frame] for frame in data.keys()) 

In [7]:
df = df.reset_index()

In [8]:
df = df.drop(labels = 'index', axis = 1)
df

State                     Agency Name  ...  Ship Date Station Type
0         AL           ABBEVILLE POLICE DEPT  ... 2018-01-30        State
1         AL           ABBEVILLE POLICE DEPT  ... 2016-06-02        State
2         AL           ABBEVILLE POLICE DEPT  ... 2016-11-09        State
3         AL           ABBEVILLE POLICE DEPT  ... 2016-09-14        State
4         AL           ABBEVILLE POLICE DEPT  ... 2017-03-28        State
...      ...                             ...  ...        ...          ...
130953    WY  WESTON COUNTY SHERIFF'S OFFICE  ... 1993-09-01        State
130954    WY  WESTON COUNTY SHERIFF'S OFFICE  ... 1993-09-01        State
130955    WY  WESTON COUNTY SHERIFF'S OFFICE  ... 1993-09-01        State
130956    WY  WESTON COUNTY SHERIFF'S OFFICE  ... 1993-09-01        State
130957    WY  WESTON COUNTY SHERIFF'S OFFICE  ... 1993-09-01        State

[130958 rows x 11 columns]

In [9]:
df.count()

State                130958
Agency Name          130958
NSN                  130958
Item Name            130958
Quantity             130958
UI                   130958
Acquisition Value    130958
DEMIL Code           130958
DEMIL IC             121048
Ship Date            130958
Station Type         130958
dtype: int64

In [10]:
# There are 814 rows that are having null values and all are from column DEMIL IC
df.isnull().sum()

State                   0
Agency Name             0
NSN                     0
Item Name               0
Quantity                0
UI                      0
Acquisition Value       0
DEMIL Code              0
DEMIL IC             9910
Ship Date               0
Station Type            0
dtype: int64

In [11]:
df = df.fillna(1)

In [12]:
# We will drop state since all the instances have station type as state which as no significance 
df.groupby('Station Type').count()['State']

Station Type
State    130958
Name: State, dtype: int64

In [13]:
df = df.drop('Station Type', 1)

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130958 entries, 0 to 130957
Data columns (total 10 columns):
 #   Column             Non-Null Count   Dtype         
---  ------             --------------   -----         
 0   State              130958 non-null  object        
 1   Agency Name        130958 non-null  object        
 2   NSN                130958 non-null  object        
 3   Item Name          130958 non-null  object        
 4   Quantity           130958 non-null  int64         
 5   UI                 130958 non-null  object        
 6   Acquisition Value  130958 non-null  float64       
 7   DEMIL Code         130958 non-null  object        
 8   DEMIL IC           130958 non-null  float64       
 9   Ship Date          130958 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(1), object(6)
memory usage: 10.0+ MB


In [15]:
from sklearn.preprocessing import LabelEncoder

le =LabelEncoder()

df['State'] = le.fit_transform(df['State'])
df['Agency Name'] = le.fit_transform(df['Agency Name'])
df['NSN'] = le.fit_transform(df['NSN'])
df['Item Name'] = le.fit_transform(df['Item Name'])
df['UI'] = le.fit_transform(df['UI'])
df['DEMIL Code'] = le.fit_transform(df['DEMIL Code'])
df['Ship Date'] = le.fit_transform(df['Ship Date'])
# df['Station Type'] = le.fit_transform(df['Station Type'])





In [16]:
df.corr()

State  Agency Name  ...  DEMIL IC  Ship Date
State              1.000000     0.007716  ...  0.009781   0.061788
Agency Name        0.007716     1.000000  ... -0.004451   0.015957
NSN                0.009308     0.021460  ...  0.160561   0.632406
Item Name          0.008374    -0.012198  ... -0.028624  -0.257155
Quantity          -0.010061     0.007939  ... -0.004195   0.099630
UI                -0.014232     0.026054  ... -0.009302   0.152234
Acquisition Value  0.001140    -0.004720  ...  0.025192   0.053920
DEMIL Code         0.005336    -0.031039  ...  0.287777  -0.392149
DEMIL IC           0.009781    -0.004451  ...  1.000000   0.166042
Ship Date          0.061788     0.015957  ...  0.166042   1.000000

[10 rows x 10 columns]

In [17]:
from tensorflow.keras.optimizers import Adam
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from keras.models import Sequential
from keras.layers import Dense



In [18]:
from sklearn.preprocessing import normalize
import keras.utils
from tensorflow.keras.utils import to_categorical

# 'State','Ship Date', 'Agency Name', 'NSN', 'Item Name', 'Acquisition Value',
#                      'DEMIL Code' , 'DEMIL IC'

X = df.drop(labels = ['DEMIL Code'], axis = 1)

y = df['DEMIL Code']

X = normalize(X)


X_train, X_test,y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = True)





In [19]:
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [20]:
X_train = np.array(X_train)
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
X_train.shape

(91670, 9, 1)

In [21]:

y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

In [22]:
model=Sequential()
model.add(Dense(4000,input_dim=X_train.shape[1], activation='relu'))
model.add(Dense(1000,activation='relu'))
model.add(Dense(500,activation='relu'))
model.add(Dense(7,activation='softmax'))



In [23]:
optimizer = Adam(learning_rate=0.0001)
model.compile(optimizer, loss='binary_crossentropy',metrics=['accuracy'])

print('Model summary')
print(model.summary())

Model summary
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 4000)              40000     
                                                                 
 dense_1 (Dense)             (None, 1000)              4001000   
                                                                 
 dense_2 (Dense)             (None, 500)               500500    
                                                                 
 dense_3 (Dense)             (None, 7)                 3507      
                                                                 
Total params: 4,545,007
Trainable params: 4,545,007
Non-trainable params: 0
_________________________________________________________________
None


In [24]:
y

0         3
1         3
2         2
3         3
4         3
         ..
130953    3
130954    3
130955    3
130956    3
130957    3
Name: DEMIL Code, Length: 130958, dtype: int64

In [25]:
model.fit(X_train, y_train, verbose=2, batch_size=64,epochs=100)

Epoch 1/100
1433/1433 - 10s - loss: 0.1147 - accuracy: 0.8363 - 10s/epoch - 7ms/step
Epoch 2/100
1433/1433 - 7s - loss: 0.0887 - accuracy: 0.8687 - 7s/epoch - 5ms/step
Epoch 3/100
1433/1433 - 7s - loss: 0.0839 - accuracy: 0.8764 - 7s/epoch - 5ms/step
Epoch 4/100
1433/1433 - 7s - loss: 0.0806 - accuracy: 0.8811 - 7s/epoch - 5ms/step
Epoch 5/100
1433/1433 - 7s - loss: 0.0779 - accuracy: 0.8846 - 7s/epoch - 5ms/step
Epoch 6/100
1433/1433 - 7s - loss: 0.0754 - accuracy: 0.8892 - 7s/epoch - 5ms/step
Epoch 7/100
1433/1433 - 7s - loss: 0.0732 - accuracy: 0.8937 - 7s/epoch - 5ms/step
Epoch 8/100
1433/1433 - 7s - loss: 0.0715 - accuracy: 0.8966 - 7s/epoch - 5ms/step
Epoch 9/100
1433/1433 - 7s - loss: 0.0696 - accuracy: 0.8998 - 7s/epoch - 5ms/step
Epoch 10/100
1433/1433 - 7s - loss: 0.0683 - accuracy: 0.9027 - 7s/epoch - 5ms/step
Epoch 11/100
1433/1433 - 7s - loss: 0.0671 - accuracy: 0.9044 - 7s/epoch - 5ms/step
Epoch 12/100
1433/1433 - 7s - loss: 0.0661 - accuracy: 0.9060 - 7s/epoch - 5ms/step

In [26]:
# X_train = np.array(X_train)
# X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
# X_train.shape

In [27]:
# from tensorflow.keras.utils import to_categorical
# #one-hot encode target column
# y_train = to_categorical(y_train)
# y_test = to_categorical(y_test)

In [28]:
y_test.shape

(39288, 7)

In [29]:
# Model 1 - ANN 
results = model.evaluate(X_test, y_test)
print('Final test set loss', format(results[0]))
print('Final test set accuracy', format(results[1]))

1228/1228 [==============================] - 4s 3ms/step - loss: 0.0290 - accuracy: 0.9654
Final test set loss 0.02896084263920784
Final test set accuracy 0.9654092788696289


In [30]:
predict = model.predict(X_test, batch_size=128)
predict

array([[9.9999750e-01, 5.1500638e-07, 2.3504073e-08, ..., 6.0033038e-08,
        1.1264157e-08, 1.2027664e-09],
       [0.0000000e+00, 6.4414441e-19, 6.4049343e-27, ..., 0.0000000e+00,
        0.0000000e+00, 4.1003516e-28],
       [0.0000000e+00, 1.1400008e-19, 2.5604591e-28, ..., 0.0000000e+00,
        0.0000000e+00, 6.6161116e-29],
       ...,
       [0.0000000e+00, 2.9071670e-18, 8.2624348e-26, ..., 0.0000000e+00,
        0.0000000e+00, 7.0273632e-27],
       [9.9667346e-01, 4.4259094e-05, 1.9902305e-04, ..., 7.7981310e-16,
        6.5074059e-06, 1.7740844e-07],
       [1.5195879e-05, 1.7921018e-04, 7.3653064e-05, ..., 3.4467793e-09,
        7.3670805e-04, 2.9627505e-05]], dtype=float32)

In [31]:
y_pred = np.argmax(predict, axis = 1)

In [32]:
# y_test_cat = to_categorical(y_test) # converting to categorial
y_val =np.argmax(y_test, axis = 1)

In [33]:
print(classification_report(y_val,y_pred))

              precision    recall  f1-score   support

           0       0.95      0.95      0.95      5424
           1       0.25      0.02      0.04        52
           2       0.89      0.86      0.87      2104
           3       0.98      0.99      0.98     28099
           4       0.79      0.56      0.66        34
           5       0.94      0.90      0.92      1905
           6       0.92      0.89      0.91      1670

    accuracy                           0.97     39288
   macro avg       0.82      0.74      0.76     39288
weighted avg       0.96      0.97      0.96     39288



In [34]:
confusion_matrix(y_val,y_pred)

array([[ 5151,     0,    20,   209,     0,     7,    37],
       [    9,     1,     2,    31,     0,     0,     9],
       [   44,     0,  1808,   160,     0,    32,    60],
       [  161,     2,   114, 27737,     5,    55,    25],
       [    4,     0,     0,    10,    19,     0,     1],
       [    8,     0,    20,   154,     0,  1723,     0],
       [   28,     1,    65,    74,     0,    12,  1490]])

In [34]:
# Balanced Dataset

In [35]:
df = pd.concat(data[frame] for frame in data.keys()) 
df = df.reset_index()
df = df.drop(labels = 'index', axis = 1)
df

State                     Agency Name  ...  Ship Date Station Type
0         AL           ABBEVILLE POLICE DEPT  ... 2018-01-30        State
1         AL           ABBEVILLE POLICE DEPT  ... 2016-06-02        State
2         AL           ABBEVILLE POLICE DEPT  ... 2016-11-09        State
3         AL           ABBEVILLE POLICE DEPT  ... 2016-09-14        State
4         AL           ABBEVILLE POLICE DEPT  ... 2017-03-28        State
...      ...                             ...  ...        ...          ...
130953    WY  WESTON COUNTY SHERIFF'S OFFICE  ... 1993-09-01        State
130954    WY  WESTON COUNTY SHERIFF'S OFFICE  ... 1993-09-01        State
130955    WY  WESTON COUNTY SHERIFF'S OFFICE  ... 1993-09-01        State
130956    WY  WESTON COUNTY SHERIFF'S OFFICE  ... 1993-09-01        State
130957    WY  WESTON COUNTY SHERIFF'S OFFICE  ... 1993-09-01        State

[130958 rows x 11 columns]

In [36]:
df = df.fillna(1)

In [37]:
# We will drop state since all the instances have station type as state which as no significance 
df.groupby('Station Type').count()['State']

Station Type
State    130958
Name: State, dtype: int64

In [38]:
df = df.drop('Station Type', 1)

In [39]:
df

State                     Agency Name  ... DEMIL IC  Ship Date
0         AL           ABBEVILLE POLICE DEPT  ...      1.0 2018-01-30
1         AL           ABBEVILLE POLICE DEPT  ...      1.0 2016-06-02
2         AL           ABBEVILLE POLICE DEPT  ...      1.0 2016-11-09
3         AL           ABBEVILLE POLICE DEPT  ...      1.0 2016-09-14
4         AL           ABBEVILLE POLICE DEPT  ...      1.0 2017-03-28
...      ...                             ...  ...      ...        ...
130953    WY  WESTON COUNTY SHERIFF'S OFFICE  ...      1.0 1993-09-01
130954    WY  WESTON COUNTY SHERIFF'S OFFICE  ...      1.0 1993-09-01
130955    WY  WESTON COUNTY SHERIFF'S OFFICE  ...      1.0 1993-09-01
130956    WY  WESTON COUNTY SHERIFF'S OFFICE  ...      1.0 1993-09-01
130957    WY  WESTON COUNTY SHERIFF'S OFFICE  ...      1.0 1993-09-01

[130958 rows x 10 columns]

In [40]:
# Sampling the dataset to 10000 for each target label so total instances together is 10000 X 7 = 70000
sample = 10000
df = df.groupby('DEMIL Code').apply(lambda x: x.sample(sample,replace=True))

df = df.droplevel(0).reset_index()
df = df.drop(labels = 'index', axis =1)

In [41]:
from sklearn.preprocessing import LabelEncoder

le =LabelEncoder()

df['State'] = le.fit_transform(df['State'])
df['Agency Name'] = le.fit_transform(df['Agency Name'])
df['NSN'] = le.fit_transform(df['NSN'])
df['Item Name'] = le.fit_transform(df['Item Name'])
df['UI'] = le.fit_transform(df['UI'])
df['DEMIL Code'] = le.fit_transform(df['DEMIL Code'])
df['Ship Date'] = le.fit_transform(df['Ship Date'])
# df['Station Type'] = le.fit_transform(df['Station Type'])


In [42]:
X = df.drop(labels = ['DEMIL Code'], axis = 1)
y = df['DEMIL Code']
# df['State']
X = normalize(X)

# y = to_categorical(y)

X_train, X_test,y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = True)



In [43]:
X_train = np.array(X_train)
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
X_train.shape


(49000, 9, 1)

In [44]:
from tensorflow.keras.utils import to_categorical
#one-hot encode target column
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

In [45]:
model_sample=Sequential()
model_sample.add(Dense(4000,input_dim=X_train.shape[1], activation='relu'))
model_sample.add(Dense(1000,activation='relu'))
model_sample.add(Dense(500,activation='relu'))
model_sample.add(Dense(7,activation='softmax'))

In [46]:
optimizer = Adam(learning_rate=0.0001)
model_sample.compile(optimizer, loss='binary_crossentropy',metrics=['accuracy'])

print('Model summary')
print(model_sample.summary())

Model summary
Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_4 (Dense)             (None, 4000)              40000     
                                                                 
 dense_5 (Dense)             (None, 1000)              4001000   
                                                                 
 dense_6 (Dense)             (None, 500)               500500    
                                                                 
 dense_7 (Dense)             (None, 7)                 3507      
                                                                 
Total params: 4,545,007
Trainable params: 4,545,007
Non-trainable params: 0
_________________________________________________________________
None


In [47]:
model_sample.fit(X_train, y_train, verbose=2, batch_size=128,epochs=100)

Epoch 1/100
383/383 - 3s - loss: 0.2977 - accuracy: 0.5587 - 3s/epoch - 8ms/step
Epoch 2/100
383/383 - 2s - loss: 0.2371 - accuracy: 0.6483 - 2s/epoch - 6ms/step
Epoch 3/100
383/383 - 2s - loss: 0.2227 - accuracy: 0.6656 - 2s/epoch - 6ms/step
Epoch 4/100
383/383 - 2s - loss: 0.2110 - accuracy: 0.6774 - 2s/epoch - 6ms/step
Epoch 5/100
383/383 - 2s - loss: 0.2025 - accuracy: 0.6910 - 2s/epoch - 6ms/step
Epoch 6/100
383/383 - 2s - loss: 0.1954 - accuracy: 0.7045 - 2s/epoch - 6ms/step
Epoch 7/100
383/383 - 2s - loss: 0.1897 - accuracy: 0.7145 - 2s/epoch - 6ms/step
Epoch 8/100
383/383 - 2s - loss: 0.1849 - accuracy: 0.7234 - 2s/epoch - 6ms/step
Epoch 9/100
383/383 - 2s - loss: 0.1801 - accuracy: 0.7306 - 2s/epoch - 6ms/step
Epoch 10/100
383/383 - 2s - loss: 0.1756 - accuracy: 0.7383 - 2s/epoch - 6ms/step
Epoch 11/100
383/383 - 2s - loss: 0.1719 - accuracy: 0.7461 - 2s/epoch - 6ms/step
Epoch 12/100
383/383 - 2s - loss: 0.1684 - accuracy: 0.7530 - 2s/epoch - 6ms/step
Epoch 13/100
383/383 - 2s

In [48]:
# Model 1 - ANN 
results_sample = model_sample.evaluate(X_test, y_test)
print('Final test set loss', format(results_sample[0]))
print('Final test set accuracy', format(results_sample[1]))

657/657 [==============================] - 2s 4ms/step - loss: 0.0671 - accuracy: 0.9241
Final test set loss 0.06707040965557098
Final test set accuracy 0.9240952134132385


In [49]:
predict_sample = model_sample.predict(X_test, batch_size=128)
predict_sample

array([[9.9966359e-01, 5.4118212e-09, 3.6949788e-09, ..., 3.2306957e-09,
        3.2737092e-04, 2.6611638e-06],
       [2.2198164e-34, 3.2056688e-12, 1.2678105e-08, ..., 9.9999464e-01,
        9.0667099e-11, 2.5451106e-07],
       [1.5594561e-16, 1.3930708e-07, 7.1604757e-07, ..., 1.7646209e-11,
        9.9997878e-01, 7.1549844e-06],
       ...,
       [9.9459261e-01, 8.6360897e-06, 5.1435933e-04, ..., 1.9169688e-09,
        7.1408867e-04, 5.0885481e-04],
       [3.8557278e-06, 1.5998914e-09, 5.5470614e-04, ..., 0.0000000e+00,
        7.4437124e-01, 2.0717319e-02],
       [0.0000000e+00, 1.6844274e-33, 1.7217628e-18, ..., 0.0000000e+00,
        3.2489142e-32, 1.3978943e-18]], dtype=float32)

In [50]:
y_pred_sample = np.argmax(predict_sample, axis = 1)

In [51]:
# y_test_cat_sample = to_categorical(y_test) # converting to categorial
y_val_sample =np.argmax(y_test, axis = 1)

In [52]:
print(classification_report(y_val_sample,y_pred_sample))

              precision    recall  f1-score   support

           0       0.94      0.92      0.93      3061
           1       0.93      0.99      0.96      3066
           2       0.81      0.92      0.86      3032
           3       0.98      0.89      0.93      2979
           4       0.99      1.00      0.99      2958
           5       0.92      0.95      0.94      2949
           6       0.92      0.80      0.85      2955

    accuracy                           0.92     21000
   macro avg       0.93      0.92      0.92     21000
weighted avg       0.93      0.92      0.92     21000



In [53]:
confusion_matrix(y_val_sample,y_pred_sample)

array([[2809,   78,   64,   22,    4,   40,   44],
       [   0, 3046,   20,    0,    0,    0,    0],
       [  46,   21, 2787,   14,    3,   83,   78],
       [  66,   50,   86, 2642,    8,   54,   73],
       [   0,    0,    0,    0, 2958,    0,    0],
       [  18,    6,   96,    2,    5, 2808,   14],
       [  50,   63,  397,    7,   14,   68, 2356]])

In [54]:
y_train[0]

array([0., 0., 1., 0., 0., 0., 0.], dtype=float32)